# Model arguments
model_name_or_path: mistralai/Mistral-7B-Instruct-v0.3
tokenizer_name_or_path: mistralai/Mistral-7B-Instruct-v0.3
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
use_liger: true
bf16: true
tf32: true
output_dir: runs/mistral-7b-inst-v3-autoinstruct-llamascout17b16e-v1

# Dataset arguments
dataset_id_or_path: /home/ubuntu/fine-tuning/train_dataset_qca_triplets_llamascout17b16e_qwen25vl34b.json
max_seq_length: 3072
packing: true

# LoRA arguments
use_peft: true
load_in_4bit: false
lora_target_modules: "all-linear"
# important as we need to train the special tokens for the chat template of llama 
# lora_modules_to_save: ['up_proj', 'down_proj', 'gate_proj', 'k_proj', 'q_proj', 'v_proj', 'o_proj']
lora_r: 2048
lora_alpha: 1024

# Training arguments
num_train_epochs: 15
per_device_train_batch_size: 10
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 1.0e-4 
lr_scheduler_type: cosine
warmup_ratio: 0.1

# Logging arguments
logging_strategy: steps
logging_steps: 2
report_to:
- wandb
save_strategy: "epoch"
seed: 42

# Hugging Face Hub 
push_to_hub: false
# hub_model_id: llama-3-1-8b-math-orca-qlora-10k-ep1 # if not defined same as output_dir
hub_strategy: every_save