# Model arguments
model_name_or_path: tiiuae/Falcon3-10B-Instruct
tokenizer_name_or_path: tiiuae/Falcon3-10B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
use_liger: false
bf16: true
tf32: true
output_dir: /tmp/hf_logs/tiiuae/Falcon3-10B-Instruct/

# Dataset arguments
dataset_id_or_path: /home/ubuntu/pranavvm/amazon-sagemaker-generativeai/3_distributed_training/sm_huggingface_oss_recipes/local-dataset/HuggingFaceH4--Multilingual-Thinking.jsonl
max_seq_length: 4096
packing: true

# Spectrum Config
spectrum_config_path: configs/spectrum/snr_results_tiiuae-Falcon3-10B-Instruct_unfrozenparameters_30percent.yaml

# Training arguments
num_train_epochs: 1
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: true
learning_rate: 1.5e-4 
lr_scheduler_type: constant
warmup_ratio: 0.1

# Logging arguments
logging_strategy: steps
logging_steps: 5
report_to:
- tensorboard
save_strategy: "epoch"
seed: 42